//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int SeatId { get; set; }
        public int ShowId { get; set; }
        public int SeatNo { get; set; }
        public string Status { get; set; }
    
        public virtual Show Show { get; set; }
    }
}
