//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        public int ShowId { get; set; }
        public int MovieId { get; set; }
        public int TheatreId { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
